### ISSUE TITLE
I can not see the src file

### ISSUE THREAD

**Issue by Jimmy66641** [StefanoGenettiUniTN/hn-moea-influence-maximization#1]
There is no code in the github repository, I really need this code for my experiments, can you upload it, thanks a lot!

**Comment by StefanoGenettiUniTN** [comment]
Thank you for your interest in our work.
Here is the GitHub repository with the source code:
GitHub repository: [https://github.com/DIOL-UniTN/hn-moea-im.git](https://github.com/DIOL-UniTN/hn-moea-im.git)
